// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { configService } from "./app/lib/ConfigService";

process.env.CONFIG_PROFILE = 'production';
await configService.init();
const connectionString = `postgresql://${process.env['datasource.username']}:${process.env['datasource.password']}@${process.env['datasource.url']}?sslmode=disable`;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: connectionString,
  },
});
