import type { Metadata } from "next";
import {ReactNode, Suspense} from "react";
import ThemeWrapper from "@/app/ThemeWrapper";
import {AppRouterCacheProvider} from "@mui/material-nextjs/v13-appRouter";
import AppHeader from "@/app/components/header/AppHeader";
import QueryProvider from "@/app/components/global/QueryProvider";

import "./globals.css";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Dungeons and Dragons Notes",
  description: "Generated by create next app"
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
  return <html>
    <body>
      <AppRouterCacheProvider options={{ enableCssLayer: true }}>
        <Suspense>
          <QueryProvider>
            <ThemeWrapper>
              <AppHeader redirect_url={process.env['discord.redirect-url'] ?? ''} client_id={process.env['discord.client.id'] ?? ''} />
              {children}
            </ThemeWrapper>
          </QueryProvider>
        </Suspense>
      </AppRouterCacheProvider>
    </body>
  </html>;
}
