import type { Metadata } from "next";
import {ReactNode} from "react";
import ThemeWrapper from "@/app/ThemeWrapper";
import {AppRouterCacheProvider} from "@mui/material-nextjs/v13-appRouter";
import "./globals.css";
import AppHeader from "@/app/components/AppHeader";
import {AuthDataProvider} from "@/app/components/auth/AuthDataProvider";

export const metadata: Metadata = {
  title: "Dungeons and Dragons Notes",
  description: "Generated by create next app"
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
  return <html>
    <body>
      <AppRouterCacheProvider options={{ enableCssLayer: true }}>
        <AuthDataProvider>
          <ThemeWrapper>
            <AppHeader redirect_url={process.env['discord.redirect-url'] ?? ''} client_id={process.env['discord.client.id'] ?? ''} />
            {children}
          </ThemeWrapper>
        </AuthDataProvider>
      </AppRouterCacheProvider>
    </body>
  </html>;
}
